name: movie_tracker
description: Movie Tracker App - локальное приложение для отслеживания фильмов.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI пакеты
  google_fonts: ^8.0.2
  convex_bottom_bar: ^3.2.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2

  # State Management
  provider: ^6.1.1

  # Backend
  supabase_flutter: ^2.0.0

  # Локальное хранилище
  shared_preferences: ^2.2.2

  # Утилиты
  fluttertoast: ^9.0.0
  http: ^1.1.0

  # Иконки
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
